"""Pairwise (2-way) combinatorial coverage over campaign-configuration space.

The claim under test is deliberately weak per cell and broad across cells: EVERY
combination of campaign-configuration choices must produce a COHERENT OUTCOME —
it compiles and runs to a report, or it fails with an actionable message naming
the problem. Never a bare stack trace, never a silently-wrong artifact.

That is the right strength for this technique here. A campaign's configuration
space is combinatorial (7 dimensions below), most interaction bugs in it are
2-way rather than n-way, and the failure mode that actually bites is not "the
answer is subtly off" — the pipeline has metamorphic tests for that — it is "this
combination raises `KeyError: 'refine'` 40 minutes into a paid campaign".

THE CIRCULARITY HAZARD, and what is done about it. Nous IS a combinatorial design
tool, so the covering array below could be generated by `orchestrator.optimize.
design.fractional_factorial`. A bug in that generator would then produce a
defective covering array that fails to cover the cell exposing the bug — the test
would hide the defect it exists to find. So:

  * the array is built by an INDEPENDENT greedy algorithm in this file
    (`_pairwise`), which shares no code with `design.py`;
  * `test_the_covering_array_really_covers_every_pair` verifies the array's
    2-way coverage property directly, by enumeration;
  * three cells are HAND-VERIFIED against hand-written expectations in
    `test_hand_verified_cells_*` — named explicitly so the non-circularity claim
    is checkable rather than asserted.

HAND-VERIFIED CELLS (stated here so a reader does not have to hunt):
  1. stages=[verify,screen,confirm], numeric factor, cli_flag, width 1,
     unconstrained, maximize, replicates 3  -> compiles; policy has no `refine`
     state; screen's default transition goes to `confirm`.
  2. stages=[verify,screen,refine,confirm] with a factor whose levels are
     2-valued  -> `refine` is DROPPED from the compiled policy (nothing is
     refinable) and screen's default still routes to `confirm`.
  3. stages=[build,verify,screen,confirm]   -> `build` is a pre-epoch stage, so
     it appears in `compiled_from.pre_epoch` and NOT as a policy state.
"""
from __future__ import annotations

import itertools
import json

import pytest

from orchestrator.optimize.factors import parse_factors
from orchestrator.optimize.policy import (
    check_policy, compile_policy, enumerate_paths, pre_epoch_stages, step,
)

pytestmark = pytest.mark.combinatorial


# ── the dimensions ─────────────────────────────────────────────────────────

DIMENSIONS: dict[str, tuple] = {
    # `build` at position 1 only; foldover/refine presence changes the policy shape.
    "stages": ("screen_only", "screen_confirm", "full", "with_build", "no_foldover"),
    "factor_type": ("numeric", "choice"),
    "apply_kind": ("cli_flag", "env", "config_patch"),
    "width": (1, 4),
    "constrained": (False, True),
    "direction": ("maximize", "minimize"),
    "replicates": (1, 3),
}


def _pairwise(dims: dict[str, tuple], *, seed: int = 0) -> list[dict]:
    """A 2-way covering array, built greedily and INDEPENDENTLY of design.py.

    Deterministic: candidate rows are enumerated in a fixed order and the one
    covering the most still-uncovered pairs wins, ties broken by that order. No
    RNG, so the array is identical on every machine — a covering array that
    varied per run would make a failure irreproducible.

    Not minimal, and does not try to be. Minimality is an optimisation problem;
    coverage is the property that matters, and it is verified separately.
    """
    keys = list(dims)
    pairs_needed = {
        ((ka, va), (kb, vb))
        for ka, kb in itertools.combinations(keys, 2)
        for va in dims[ka] for vb in dims[kb]
    }
    # Enumerating the full cross product is fine at this size (5*2*3*2*2*2*2=480)
    # and keeps the algorithm obviously correct.
    candidates = [dict(zip(keys, combo))
                  for combo in itertools.product(*(dims[k] for k in keys))]
    rows: list[dict] = []
    while pairs_needed:
        best, best_gain = None, -1
        for cand in candidates:
            gain = sum(
                1 for (ka, va), (kb, vb) in pairs_needed
                if cand[ka] == va and cand[kb] == vb
            )
            if gain > best_gain:
                best, best_gain = cand, gain
        assert best is not None and best_gain > 0, "covering array made no progress"
        rows.append(best)
        pairs_needed = {
            p for p in pairs_needed
            if not (best[p[0][0]] == p[0][1] and best[p[1][0]] == p[1][1])
        }
    return rows


COVERING_ARRAY = _pairwise(DIMENSIONS)


def _cell_id(cell: dict) -> str:
    return ",".join(f"{k}={cell[k]}" for k in DIMENSIONS)


# ── array self-verification (the anti-circularity guard) ──────────────────


def test_the_covering_array_really_covers_every_pair():
    """Verified by ENUMERATION, not by trusting the generator.

    If this fails, every cell test below is testing less than it claims and the
    suite would still be green — so this assertion has to come first.
    """
    covered = set()
    for row in COVERING_ARRAY:
        for ka, kb in itertools.combinations(DIMENSIONS, 2):
            covered.add(((ka, row[ka]), (kb, row[kb])))
    expected = {
        ((ka, va), (kb, vb))
        for ka, kb in itertools.combinations(DIMENSIONS, 2)
        for va in DIMENSIONS[ka] for vb in DIMENSIONS[kb]
    }
    missing = expected - covered
    assert not missing, f"{len(missing)} pairs uncovered, e.g. {sorted(missing)[:5]}"


def test_the_covering_array_is_far_smaller_than_the_full_cross_product():
    """The whole economic argument for pairwise, stated numerically.

    If the array were the same size as the cross product this technique would be
    buying nothing over exhaustive enumeration.
    """
    full = 1
    for vals in DIMENSIONS.values():
        full *= len(vals)
    assert full == 480
    assert len(COVERING_ARRAY) < full / 10, (
        f"{len(COVERING_ARRAY)} rows for {full} combinations is not a useful "
        f"reduction"
    )


def test_the_covering_array_is_deterministic_across_calls():
    """A failing cell must be reproducible, so the array cannot vary."""
    assert _pairwise(DIMENSIONS) == COVERING_ARRAY
    assert json.dumps(COVERING_ARRAY, sort_keys=True) == json.dumps(
        _pairwise(DIMENSIONS), sort_keys=True)


# ── building a campaign from a cell ───────────────────────────────────────


_STAGE_LISTS = {
    "screen_only": ["verify", "screen"],
    "screen_confirm": ["verify", "screen", "confirm"],
    "full": ["verify", "screen", "refine", "confirm"],
    "with_build": ["build", "verify", "screen", "confirm"],
    "no_foldover": ["verify", "screen", "refine", "confirm"],
}


def _apply_for(kind: str, fid: str) -> dict:
    """The three apply kinds in the shapes `matrix._render_apply` actually reads.

    Field names taken from that function rather than invented: `cli_flag` needs
    `template`, `env_var` needs `name` + `value`, `config_patch` needs `path` +
    `pointer` + `value`. A cell built from guessed field names would fail with a
    KeyError and be indistinguishable from the incoherent-outcome defect this
    sweep exists to detect.
    """
    return {
        "cli_flag": {"kind": "cli_flag", "template": f"--{fid.lower()}={{level}}"},
        "env": {"kind": "env_var", "name": f"NOUS_{fid.upper()}",
                "value": "{level}"},
        "config_patch": {"kind": "config_patch", "path": "config.yaml",
                         "pointer": f"/cfg/{fid.lower()}", "value": "{level}"},
    }[kind]


def _campaign_for(cell: dict) -> dict:
    fid = "A"
    if cell["factor_type"] == "numeric":
        factor = {"id": fid, "type": "numeric", "levels": [2, 4, 8, 16], "grid": 1}
    else:
        factor = {"id": fid, "type": "choice", "levels": ["off", "on"]}
    factor["apply"] = _apply_for(cell["apply_kind"], fid)
    factor["manipulation"] = {"observable": f"cfg.{fid.lower()}", "op": "==",
                              "value": "{level}"}
    factor["relations"] = [{"kind": "correctness", "native_test": "tests/test_a.py"}]

    second = {"id": "B", "type": "choice", "levels": ["off", "on"],
              "apply": _apply_for(cell["apply_kind"], "B"),
              "manipulation": {"observable": "cfg.b", "op": "==", "value": "{level}"},
              "relations": [{"kind": "correctness", "native_test": "tests/test_b.py"}]}

    response: dict = {"primary": {"metric": "m", "direction": cell["direction"]}}
    if cell["constrained"]:
        response["constraints"] = [{"metric": "p99", "op": "<", "value": 250.0}]

    opt: dict = {
        "stages": list(_STAGE_LISTS[cell["stages"]]),
        "response": response,
        "factors": [factor, second],
        "max_parallel": cell["width"],
        "design": {
            "screen": {"resolution": 5, "center_points": 4},
            "refine": {"kind": "central_composite", "center_points": 4},
            "confirm": {"shortlist_size": 3, "replicates": cell["replicates"]},
        },
        "known_valid_baseline": {"A": 2 if cell["factor_type"] == "numeric" else "off",
                                 "B": "off"},
        "workload": {"seed_env": "NOUS_WORKLOAD_SEED"},
    }
    if cell["stages"] == "no_foldover":
        opt["policy"] = {"foldover": False}
    return {"kind": "optimization", "run_id": "pw", "research_question": "q",
            "target_system": {"name": "t", "description": "d"},
            "optimization": opt}


# ── the cell sweep ────────────────────────────────────────────────────────


@pytest.mark.parametrize("cell", COVERING_ARRAY, ids=_cell_id)
def test_every_cell_either_compiles_a_valid_policy_or_says_why_not(cell):
    """THE COHERENT-OUTCOME CLAIM.

    Success means: a policy that passes its own structural check, whose paths all
    terminate, and where `step` is total from every non-terminal state. Failure
    means a ValueError whose message names the problem. A `KeyError`, an
    `AttributeError`, a `TypeError`, or an `AssertionError` is NEVER a coherent
    outcome — those are the shapes of "this combination was never considered".
    """
    campaign = _campaign_for(cell)
    try:
        pol = compile_policy(campaign)
    except ValueError as exc:
        assert str(exc).strip(), "refused a campaign with an empty message"
        return
    except (KeyError, AttributeError, TypeError, IndexError, AssertionError) as exc:
        pytest.fail(
            f"cell {_cell_id(cell)} produced an INCOHERENT failure "
            f"{type(exc).__name__}: {exc} — a configuration combination nobody "
            f"considered, surfacing as a crash rather than a refusal"
        )

    assert check_policy(pol) == [], (_cell_id(cell), check_policy(pol))
    for p in enumerate_paths(pol):
        assert pol["states"][p[-1]].get("terminal"), (_cell_id(cell), p)
    for state, st_ in pol["states"].items():
        if st_.get("terminal"):
            continue
        nxt, rule = step(pol, state, {})
        assert nxt in pol["states"] and "default" in rule


@pytest.mark.parametrize("cell", COVERING_ARRAY, ids=_cell_id)
def test_every_cells_factors_parse_and_their_apply_kind_round_trips(cell):
    """Each `apply.kind` is a real render path, not just a string in YAML.

    `cli_flag` / `env` / `config_patch` are three different mechanisms for
    putting a level into the target's hands; a cell whose factors parse but whose
    apply cannot render would fail at the measurement seam, after runs were paid
    for.
    """
    from orchestrator.optimize.matrix import render_apply

    factors = parse_factors(_campaign_for(cell)["optimization"]["factors"])
    assert len(factors) == 2
    levels = {f.id: f.levels[0] for f in factors}
    applied = render_apply(factors, levels)
    assert isinstance(applied, dict) and applied, (
        f"{_cell_id(cell)}: apply rendered nothing"
    )


@pytest.mark.parametrize("cell", COVERING_ARRAY, ids=_cell_id)
def test_the_declared_stage_list_and_the_compiled_states_agree(cell):
    """No stage is silently dropped, and none is silently invented.

    Two directions, both real failure modes:
      * a declared spending stage missing from the policy means the campaign
        pre-registers a design it will never execute;
      * a policy state the campaign never declared means the epoch can spend runs
        on a stage the author did not authorise.
    `refine` is the one legitimate drop (nothing refinable), and `build`/`verify`
    are legitimately pre-epoch rather than states — both asserted explicitly
    rather than waved through.
    """
    campaign = _campaign_for(cell)
    pol = compile_policy(campaign)
    declared = set(campaign["optimization"]["stages"])
    pre = set(pre_epoch_stages(campaign))
    states = set(pol["states"])

    assert pre <= declared
    assert not (pre & states), (
        f"{_cell_id(cell)}: pre-epoch stage(s) {sorted(pre & states)} also "
        f"appear as policy states"
    )
    # `foldover` is the one spending state that is NOT a declared stage, by
    # design: it is screen's REGISTERED BRANCH, on by default and gated at
    # runtime by `alias_consequential` / `foldover_affordable`. Compilation
    # cannot know whether an alias will turn out consequential — that is a fact
    # about measurements — so the branch is always registered when screen exists,
    # and `policy.foldover: false` is how a campaign declines it. Excluding it
    # from this check is therefore correct rather than a concession; the
    # `no_foldover` cell asserts the opt-out removes state and branch together.
    spending = {s for s, v in pol["states"].items() if v.get("spends")}
    undeclared_spending = spending - declared - {"foldover"}
    assert not undeclared_spending, (
        f"{_cell_id(cell)}: policy spends at {sorted(undeclared_spending)}, "
        f"which the campaign never declared"
    )
    if "foldover" in spending:
        assert ((campaign["optimization"].get("policy") or {})
                .get("foldover", True) is not False)
    dropped = (declared - pre - states) - {"report", "exception"}
    refinable = any(f.type == "numeric" and len(f.levels) > 2
                    for f in parse_factors(campaign["optimization"]["factors"]))
    if dropped:
        assert dropped == {"refine"} and not refinable, (
            f"{_cell_id(cell)}: stage(s) {sorted(dropped)} were dropped for a "
            f"reason other than 'nothing is refinable'"
        )


@pytest.mark.parametrize("cell", COVERING_ARRAY, ids=_cell_id)
def test_direction_and_constraints_survive_compilation_into_the_policy(cell):
    """The two fields a wrong answer depends on most directly.

    `direction` flips every argmax in `decide` and every contrast sign in
    `certificate`; a constraint is what makes a region INVALID rather than merely
    bad. Either silently lost at compile time produces a confidently wrong
    recommendation rather than an error.
    """
    campaign = _campaign_for(cell)
    pol = compile_policy(campaign)
    assert pol["objective"]["direction"] == cell["direction"]
    assert pol["objective"]["metric"] == "m"
    assert pol["known_valid_baseline"] == campaign["optimization"]["known_valid_baseline"]
    assert (pol["workload"] or {}).get("seed_env") == "NOUS_WORKLOAD_SEED"


# ── the hand-verified cells (non-circularity, made checkable) ─────────────


def test_hand_verified_cell_1_screen_then_confirm_has_no_refine_state():
    """HAND-VERIFIED CELL 1. Expectations written from the spec, not generated.

    stages=[verify,screen,confirm], numeric 4-level factor, cli_flag, width 1,
    unconstrained, maximize, replicates 3.

    By hand: `verify` is pre-epoch; the epoch's states are screen, confirm,
    report, exception (plus foldover, on by default). `refine` was never declared,
    so screen's DEFAULT transition must go to `confirm`.
    """
    cell = {"stages": "screen_confirm", "factor_type": "numeric",
            "apply_kind": "cli_flag", "width": 1, "constrained": False,
            "direction": "maximize", "replicates": 3}
    pol = compile_policy(_campaign_for(cell))
    assert set(pol["states"]) == {"screen", "foldover", "confirm", "report",
                                 "exception"}
    assert "refine" not in pol["states"]
    assert pre_epoch_stages(_campaign_for(cell)) == ["verify"]
    assert step(pol, "screen", {})[0] == "confirm"
    assert step(pol, "confirm", {"certified": True})[0] == "report"
    assert check_policy(pol) == []


def test_hand_verified_cell_2_refine_is_dropped_when_no_factor_is_refinable():
    """HAND-VERIFIED CELL 2.

    stages=[verify,screen,refine,confirm] with a CHOICE factor and a 2-level
    choice second factor: `is_refinable` needs a numeric factor with MORE THAN
    two levels, so nothing qualifies.

    By hand: `refine` must be absent from the policy — a central composite over
    categorical axes would fit quadratics to a factor that has no interior — and
    screen's default must therefore go to `confirm`, not to a missing state.
    """
    cell = {"stages": "full", "factor_type": "choice", "apply_kind": "env",
            "width": 4, "constrained": True, "direction": "minimize",
            "replicates": 1}
    pol = compile_policy(_campaign_for(cell))
    assert "refine" not in pol["states"], (
        "compiled a refine state with no refinable factor"
    )
    assert step(pol, "screen", {"refinable_survivors": 2})[0] != "refine"
    assert step(pol, "screen", {})[0] == "confirm"
    assert not any(t.get("to") == "refine" for t in pol["transitions"]), (
        "a transition targets a state the policy does not declare"
    )
    assert check_policy(pol) == []


def test_hand_verified_cell_3_build_is_a_pre_epoch_stage_not_a_policy_state():
    """HAND-VERIFIED CELL 3.

    stages=[build,verify,screen,confirm].

    By hand: `build` spends the campaign's ONE substantive model call and is not
    part of the compiled epoch at all — no model call is ever made inside a
    compiled epoch state, so `build` cannot be one. It must appear in
    `compiled_from.pre_epoch` and NOT in `states`.
    """
    cell = {"stages": "with_build", "factor_type": "numeric",
            "apply_kind": "config_patch", "width": 4, "constrained": True,
            "direction": "minimize", "replicates": 1}
    campaign = _campaign_for(cell)
    pol = compile_policy(campaign)
    assert pre_epoch_stages(campaign) == ["build", "verify"]
    assert pol["compiled_from"]["pre_epoch"] == ["build", "verify"]
    assert "build" not in pol["states"] and "verify" not in pol["states"]
    assert check_policy(pol) == []


def test_hand_verified_cell_4_foldover_false_removes_state_and_branch_together():
    """HAND-VERIFIED CELL 4 (the `no_foldover` dimension value).

    By hand: `policy.foldover: false` must remove BOTH the state and the
    transition into it. A registered branch that can never fire is worse than an
    absent one — `enumerate_paths` would report a path the campaign cannot take.
    """
    cell = {"stages": "no_foldover", "factor_type": "numeric",
            "apply_kind": "cli_flag", "width": 1, "constrained": False,
            "direction": "maximize", "replicates": 3}
    pol = compile_policy(_campaign_for(cell))
    assert "foldover" not in pol["states"]
    assert not any(t.get("to") == "foldover" or t.get("from") == "foldover"
                   for t in pol["transitions"])
    assert step(pol, "screen", {"alias_consequential": True,
                                "foldover_affordable": True})[0] != "foldover"
    assert check_policy(pol) == []
    assert all("foldover" not in p for p in enumerate_paths(pol))
